# Generated by Django 4.2.2 on 2023-06-25 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Railway_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.RenameField(
            model_name='register',
            old_name='add',
            new_name='address',
        ),
        migrations.RenameModel(
            old_name='Passanger',
            new_name='Passenger',
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=20, unique=True)),
                ('seat_number', models.CharField(max_length=10)),
                ('fare', models.DecimalField(decimal_places=2, max_digits=8)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Railway_app.passenger')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Railway_app.add_train')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('coach_type', models.CharField(max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Railway_app.add_train')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=20)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Railway_app.passenger')),
            ],
        ),
        migrations.CreateModel(
            name='TrainSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Railway_app.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Railway_app.add_train')),
            ],
            options={
                'ordering': ['train', 'departure_time'],
                'unique_together': {('train', 'station')},
            },
        ),
    ]
