# Generated by Django 4.2.2 on 2023-06-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Railway_app', '0002_station_rename_add_register_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='PNR',
            field=models.IntegerField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='train_no',
            field=models.IntegerField(max_length=2, null=True),
        ),
    ]
