# Generated by Django 4.2.2 on 2023-06-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Railway_app', '0003_ticket_pnr_ticket_train_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_train',
            name='travel_time',
        ),
        migrations.AlterField(
            model_name='add_train',
            name='arrival_time',
            field=models.DateTimeField(null=True, verbose_name='Arrival'),
        ),
        migrations.AlterField(
            model_name='add_train',
            name='departure_time',
            field=models.DateTimeField(null=True, verbose_name='Departure'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='PNR',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='train_no',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
