# Generated by Django 4.2.2 on 2023-06-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Railway_app', '0004_remove_add_train_travel_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='train_no',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
