# Generated by Django 4.2.2 on 2023-07-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Railway_app', '0005_alter_ticket_train_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='train',
        ),
        migrations.RenameField(
            model_name='passenger',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='passenger',
            name='email_id',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='trainschedule',
            name='station',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='Add_route',
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
        migrations.DeleteModel(
            name='Station',
        ),
    ]
