# Generated by Django 4.2.2 on 2023-07-01 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Railway_app', '0006_remove_seat_train_rename_name_passenger_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='user',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
