# Generated by Django 4.2.2 on 2023-07-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Railway_app', '0008_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='train',
            new_name='train_no',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='route',
        ),
        migrations.AddField(
            model_name='passenger',
            name='from_city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='to_city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='email_id',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='train_no',
            field=models.IntegerField(null=True),
        ),
    ]
