# Generated by Django 4.2.2 on 2023-07-02 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Railway_app', '0009_rename_train_passenger_train_no_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
