# Generated by Django 4.2.2 on 2023-07-02 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Railway_app', '0010_delete_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='status',
        ),
    ]
