# Generated by Django 4.2.2 on 2023-07-02 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Railway_app', '0012_passenger_payment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='last_name',
        ),
    ]
